// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: daos_xr.proto

package daos_xr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Capability_GetCapabilities_FullMethodName = "/daos_xr.Capability/GetCapabilities"
)

// CapabilityClient is the client API for Capability service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Capability handle, kept as a SEPARATE service so a backend that knows nothing of
// it (the Cloak proxy) simply does not serve it.
type CapabilityClient interface {
	GetCapabilities(ctx context.Context, in *CapabilitiesReq, opts ...grpc.CallOption) (*CapabilitiesPb, error)
}

type capabilityClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityClient(cc grpc.ClientConnInterface) CapabilityClient {
	return &capabilityClient{cc}
}

func (c *capabilityClient) GetCapabilities(ctx context.Context, in *CapabilitiesReq, opts ...grpc.CallOption) (*CapabilitiesPb, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesPb)
	err := c.cc.Invoke(ctx, Capability_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilityServer is the server API for Capability service.
// All implementations must embed UnimplementedCapabilityServer
// for forward compatibility
//
// Capability handle, kept as a SEPARATE service so a backend that knows nothing of
// it (the Cloak proxy) simply does not serve it.
type CapabilityServer interface {
	GetCapabilities(context.Context, *CapabilitiesReq) (*CapabilitiesPb, error)
	mustEmbedUnimplementedCapabilityServer()
}

// UnimplementedCapabilityServer must be embedded to have forward compatible implementations.
type UnimplementedCapabilityServer struct {
}

func (UnimplementedCapabilityServer) GetCapabilities(context.Context, *CapabilitiesReq) (*CapabilitiesPb, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedCapabilityServer) mustEmbedUnimplementedCapabilityServer() {}

// UnsafeCapabilityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityServer will
// result in compilation errors.
type UnsafeCapabilityServer interface {
	mustEmbedUnimplementedCapabilityServer()
}

func RegisterCapabilityServer(s grpc.ServiceRegistrar, srv CapabilityServer) {
	s.RegisterService(&Capability_ServiceDesc, srv)
}

func _Capability_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capability_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServer).GetCapabilities(ctx, req.(*CapabilitiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Capability_ServiceDesc is the grpc.ServiceDesc for Capability service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Capability_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daos_xr.Capability",
	HandlerType: (*CapabilityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _Capability_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daos_xr.proto",
}

const (
	BackendIngress_BackendSession_FullMethodName = "/daos_xr.BackendIngress/BackendSession"
	BackendIngress_UnionSession_FullMethodName   = "/daos_xr.BackendIngress/UnionSession"
)

// BackendIngressClient is the client API for BackendIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Backend gRPC ingress -- used only when an orchestrator dials the backend.
type BackendIngressClient interface {
	BackendSession(ctx context.Context, opts ...grpc.CallOption) (BackendIngress_BackendSessionClient, error)
	UnionSession(ctx context.Context, opts ...grpc.CallOption) (BackendIngress_UnionSessionClient, error)
}

type backendIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendIngressClient(cc grpc.ClientConnInterface) BackendIngressClient {
	return &backendIngressClient{cc}
}

func (c *backendIngressClient) BackendSession(ctx context.Context, opts ...grpc.CallOption) (BackendIngress_BackendSessionClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackendIngress_ServiceDesc.Streams[0], BackendIngress_BackendSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &backendIngressBackendSessionClient{ClientStream: stream}
	return x, nil
}

type BackendIngress_BackendSessionClient interface {
	Send(*BatchRequestPb) error
	Recv() (*BatchResponsePb, error)
	grpc.ClientStream
}

type backendIngressBackendSessionClient struct {
	grpc.ClientStream
}

func (x *backendIngressBackendSessionClient) Send(m *BatchRequestPb) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backendIngressBackendSessionClient) Recv() (*BatchResponsePb, error) {
	m := new(BatchResponsePb)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backendIngressClient) UnionSession(ctx context.Context, opts ...grpc.CallOption) (BackendIngress_UnionSessionClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackendIngress_ServiceDesc.Streams[1], BackendIngress_UnionSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &backendIngressUnionSessionClient{ClientStream: stream}
	return x, nil
}

type BackendIngress_UnionSessionClient interface {
	Send(*BatchRequestPb) error
	Recv() (*BatchResponsePb, error)
	grpc.ClientStream
}

type backendIngressUnionSessionClient struct {
	grpc.ClientStream
}

func (x *backendIngressUnionSessionClient) Send(m *BatchRequestPb) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backendIngressUnionSessionClient) Recv() (*BatchResponsePb, error) {
	m := new(BatchResponsePb)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BackendIngressServer is the server API for BackendIngress service.
// All implementations must embed UnimplementedBackendIngressServer
// for forward compatibility
//
// Backend gRPC ingress -- used only when an orchestrator dials the backend.
type BackendIngressServer interface {
	BackendSession(BackendIngress_BackendSessionServer) error
	UnionSession(BackendIngress_UnionSessionServer) error
	mustEmbedUnimplementedBackendIngressServer()
}

// UnimplementedBackendIngressServer must be embedded to have forward compatible implementations.
type UnimplementedBackendIngressServer struct {
}

func (UnimplementedBackendIngressServer) BackendSession(BackendIngress_BackendSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method BackendSession not implemented")
}
func (UnimplementedBackendIngressServer) UnionSession(BackendIngress_UnionSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method UnionSession not implemented")
}
func (UnimplementedBackendIngressServer) mustEmbedUnimplementedBackendIngressServer() {}

// UnsafeBackendIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendIngressServer will
// result in compilation errors.
type UnsafeBackendIngressServer interface {
	mustEmbedUnimplementedBackendIngressServer()
}

func RegisterBackendIngressServer(s grpc.ServiceRegistrar, srv BackendIngressServer) {
	s.RegisterService(&BackendIngress_ServiceDesc, srv)
}

func _BackendIngress_BackendSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackendIngressServer).BackendSession(&backendIngressBackendSessionServer{ServerStream: stream})
}

type BackendIngress_BackendSessionServer interface {
	Send(*BatchResponsePb) error
	Recv() (*BatchRequestPb, error)
	grpc.ServerStream
}

type backendIngressBackendSessionServer struct {
	grpc.ServerStream
}

func (x *backendIngressBackendSessionServer) Send(m *BatchResponsePb) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backendIngressBackendSessionServer) Recv() (*BatchRequestPb, error) {
	m := new(BatchRequestPb)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BackendIngress_UnionSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackendIngressServer).UnionSession(&backendIngressUnionSessionServer{ServerStream: stream})
}

type BackendIngress_UnionSessionServer interface {
	Send(*BatchResponsePb) error
	Recv() (*BatchRequestPb, error)
	grpc.ServerStream
}

type backendIngressUnionSessionServer struct {
	grpc.ServerStream
}

func (x *backendIngressUnionSessionServer) Send(m *BatchResponsePb) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backendIngressUnionSessionServer) Recv() (*BatchRequestPb, error) {
	m := new(BatchRequestPb)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BackendIngress_ServiceDesc is the grpc.ServiceDesc for BackendIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daos_xr.BackendIngress",
	HandlerType: (*BackendIngressServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BackendSession",
			Handler:       _BackendIngress_BackendSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UnionSession",
			Handler:       _BackendIngress_UnionSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "daos_xr.proto",
}

const (
	OrchestratorIngress_ClientSession_FullMethodName   = "/daos_xr.OrchestratorIngress/ClientSession"
	OrchestratorIngress_XrClientSession_FullMethodName = "/daos_xr.OrchestratorIngress/XrClientSession"
)

// OrchestratorIngressClient is the client API for OrchestratorIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Orchestrator gRPC ingress -- used by clients that opted into the orchestrator path.
type OrchestratorIngressClient interface {
	ClientSession(ctx context.Context, opts ...grpc.CallOption) (OrchestratorIngress_ClientSessionClient, error)
	// XR-native streaming path. The orchestrator flattens + splits each tile into
	// storage blocks internally; the backend contract is unchanged.
	XrClientSession(ctx context.Context, opts ...grpc.CallOption) (OrchestratorIngress_XrClientSessionClient, error)
}

type orchestratorIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorIngressClient(cc grpc.ClientConnInterface) OrchestratorIngressClient {
	return &orchestratorIngressClient{cc}
}

func (c *orchestratorIngressClient) ClientSession(ctx context.Context, opts ...grpc.CallOption) (OrchestratorIngress_ClientSessionClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorIngress_ServiceDesc.Streams[0], OrchestratorIngress_ClientSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorIngressClientSessionClient{ClientStream: stream}
	return x, nil
}

type OrchestratorIngress_ClientSessionClient interface {
	Send(*ClientRequestPb) error
	Recv() (*ClientResponsePb, error)
	grpc.ClientStream
}

type orchestratorIngressClientSessionClient struct {
	grpc.ClientStream
}

func (x *orchestratorIngressClientSessionClient) Send(m *ClientRequestPb) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orchestratorIngressClientSessionClient) Recv() (*ClientResponsePb, error) {
	m := new(ClientResponsePb)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orchestratorIngressClient) XrClientSession(ctx context.Context, opts ...grpc.CallOption) (OrchestratorIngress_XrClientSessionClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorIngress_ServiceDesc.Streams[1], OrchestratorIngress_XrClientSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorIngressXrClientSessionClient{ClientStream: stream}
	return x, nil
}

type OrchestratorIngress_XrClientSessionClient interface {
	Send(*XrRequestPb) error
	Recv() (*XrResponsePb, error)
	grpc.ClientStream
}

type orchestratorIngressXrClientSessionClient struct {
	grpc.ClientStream
}

func (x *orchestratorIngressXrClientSessionClient) Send(m *XrRequestPb) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orchestratorIngressXrClientSessionClient) Recv() (*XrResponsePb, error) {
	m := new(XrResponsePb)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrchestratorIngressServer is the server API for OrchestratorIngress service.
// All implementations must embed UnimplementedOrchestratorIngressServer
// for forward compatibility
//
// Orchestrator gRPC ingress -- used by clients that opted into the orchestrator path.
type OrchestratorIngressServer interface {
	ClientSession(OrchestratorIngress_ClientSessionServer) error
	// XR-native streaming path. The orchestrator flattens + splits each tile into
	// storage blocks internally; the backend contract is unchanged.
	XrClientSession(OrchestratorIngress_XrClientSessionServer) error
	mustEmbedUnimplementedOrchestratorIngressServer()
}

// UnimplementedOrchestratorIngressServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorIngressServer struct {
}

func (UnimplementedOrchestratorIngressServer) ClientSession(OrchestratorIngress_ClientSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientSession not implemented")
}
func (UnimplementedOrchestratorIngressServer) XrClientSession(OrchestratorIngress_XrClientSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method XrClientSession not implemented")
}
func (UnimplementedOrchestratorIngressServer) mustEmbedUnimplementedOrchestratorIngressServer() {}

// UnsafeOrchestratorIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorIngressServer will
// result in compilation errors.
type UnsafeOrchestratorIngressServer interface {
	mustEmbedUnimplementedOrchestratorIngressServer()
}

func RegisterOrchestratorIngressServer(s grpc.ServiceRegistrar, srv OrchestratorIngressServer) {
	s.RegisterService(&OrchestratorIngress_ServiceDesc, srv)
}

func _OrchestratorIngress_ClientSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestratorIngressServer).ClientSession(&orchestratorIngressClientSessionServer{ServerStream: stream})
}

type OrchestratorIngress_ClientSessionServer interface {
	Send(*ClientResponsePb) error
	Recv() (*ClientRequestPb, error)
	grpc.ServerStream
}

type orchestratorIngressClientSessionServer struct {
	grpc.ServerStream
}

func (x *orchestratorIngressClientSessionServer) Send(m *ClientResponsePb) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orchestratorIngressClientSessionServer) Recv() (*ClientRequestPb, error) {
	m := new(ClientRequestPb)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _OrchestratorIngress_XrClientSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrchestratorIngressServer).XrClientSession(&orchestratorIngressXrClientSessionServer{ServerStream: stream})
}

type OrchestratorIngress_XrClientSessionServer interface {
	Send(*XrResponsePb) error
	Recv() (*XrRequestPb, error)
	grpc.ServerStream
}

type orchestratorIngressXrClientSessionServer struct {
	grpc.ServerStream
}

func (x *orchestratorIngressXrClientSessionServer) Send(m *XrResponsePb) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orchestratorIngressXrClientSessionServer) Recv() (*XrRequestPb, error) {
	m := new(XrRequestPb)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrchestratorIngress_ServiceDesc is the grpc.ServiceDesc for OrchestratorIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "daos_xr.OrchestratorIngress",
	HandlerType: (*OrchestratorIngressServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientSession",
			Handler:       _OrchestratorIngress_ClientSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "XrClientSession",
			Handler:       _OrchestratorIngress_XrClientSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "daos_xr.proto",
}
